# Generated by Django 4.2.11 on 2024-04-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_profile_alter_invoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_date',
        ),
    ]
